version: "custom_cuda"  # Options: "custom_cuda" or "pytorch_cuda" or "cublas"
method: "cpp_ext" # Options: python C++ extension pybind

data: "synthetic" # Options: "mnist" or "synthetic"
  
mnist:
  batch_size: 64 # Int power of 2 

synthetic_data:
  input_size: 1000 # Int
  classes: 10 # Int
  train_samples: 10000 # Int
  test_samples: 4000 # Int
  batch_size: 64 # Int power of 2 

profile: True  # Boolean
workflow: "profile_forward_backward" # Options: "training" or "profile_forward_backward"
epochs: 2
